Call handleEnd and fetchRow always with runOnContext
vert-x3/vertx-cassandra-client pull request #62
Opened 2020-09-03 08:07 UTC by Sammers21

Closes #61

2020-09-03 08:08 UTC, Sammers21 commented
@tsegismont, can you review this PR, please.

2020-09-04 08:58 UTC, tsegismont requested changes
Thanks @Sammers21. A few changes needed

2020-09-04 08:58 UTC, tsegismont commented on src/main/java/io/vertx/cassandra/impl/CassandraRowStreamImpl.java
> +    Context ctx = context != Vertx.currentContext() ? context : Vertx.currentContext();
No need to capture the current context, we should always invoke the stream callbacks on the context that was bound to it at creation time.
```suggestion
```

2020-09-04 08:58 UTC, tsegismont commented on src/main/java/io/vertx/cassandra/impl/CassandraRowStreamImpl.java
> +      ctx.runOnContext(v -> handleEnd());
```suggestion
      context.runOnContext(v -> handleEnd());
```

2020-09-04 08:58 UTC, tsegismont commented on src/main/java/io/vertx/cassandra/impl/CassandraRowStreamImpl.java
> +        ctx.runOnContext(v -> fetchRow());
```suggestion
        context.runOnContext(v -> fetchRow());
```

2020-10-26 10:51 UTC, Sammers21 commented
@tsegismont, can you review the PR one more time, please?

2020-11-02 17:39 UTC, tsegismont approved these changes
LGTM, thanks @Sammers21 !

2020-11-02 17:40 UTC, merged